-- MySQL Script generated by MySQL Workbench
-- Tue May 30 13:37:40 2017
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`keyissue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`keyissue` (
  `ki_id` INT NULL AUTO_INCREMENT,
  `issue` VARCHAR(200) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`ki_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`politiker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`politiker` (
  `p_id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `town` VARCHAR(50) NULL,
  `parti` VARCHAR(45) NULL,
  `Fk_ki_id` INT NULL,
  PRIMARY KEY (`p_id`),
  INDEX `Fk_ki_id_idx` (`Fk_ki_id` ASC),
  CONSTRAINT `Fk_ki_id`
    FOREIGN KEY (`Fk_ki_id`)
    REFERENCES `mydb`.`keyissue` (`ki_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`news` (
  `n_id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `phonenb` VARCHAR(45) NULL,
  `town_n` VARCHAR(45) NULL,
  `Fk_p_id` INT NULL,
  PRIMARY KEY (`n_id`),
  INDEX `Fk_p_id_idx` (`Fk_p_id` ASC),
  CONSTRAINT `Fk_p_id`
    FOREIGN KEY (`Fk_p_id`)
    REFERENCES `mydb`.`politiker` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
